---
# tasks file for Ubuntu1804-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Ubuntu 18.04. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - not ansible_distribution == "Ubuntu"
      - not ansible_distribution_release == "bionic"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include: prelim.yml
  become: true
  tags:
      - prelim_tasks
      - always

- include: section1.yml
  become: true
  when: ubuntu1804cis_section1
  tags: section1

- include: section2.yml
  become: true
  when: ubuntu1804cis_section2
  tags: section2

- include: section3.yml
  become: true
  when: ubuntu1804cis_section3
  tags: section3

- include: section4.yml
  become: true
  when: ubuntu1804cis_section4
  tags: section4

- include: section5.yml
  become: true
  when: ubuntu1804cis_section5
  tags: section5

- include: section6.yml
  become: true
  when: ubuntu1804cis_section6
  tags: section6

- include: post.yml
  become: true
  tags:
      - post_tasks
      - always
