---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint -c .ansible-lint
platforms:
  - name: instance
    image: florianutz/docker-systemd:18.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint -c .ansible-lint
    enabled: true
  config_options:
    defaults:
      bin_ansible_callbacks: True
      callback_whitelist: profile_tasks,timer
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
      conditional_bare_variables: false
    connection:
      pipelining: true
scenario:
  name: default
verifier:
  name: ansible
